---

- name: information
  hosts: all
  gather_facts: true

  pre_tasks:
    - name: arch- / artixlinux
      when:
        - ansible_facts.distribution | lower == 'archlinux' or
          ansible_facts.os_family | lower == 'artix linux'
      block:
        - name: update pacman system
          ansible.builtin.command: |
            pacman --refresh --sync --sysupgrade --noconfirm

        - name: create depends service
          ansible.builtin.copy:
            mode: 0755
            dest: /etc/init.d/net
            content: |
              #!/usr/bin/openrc-run
              true
          when:
            - ansible_facts.os_family | lower == 'artix linux'

    - name: environment
      ansible.builtin.debug:
        msg:
          - "os family            : {{ ansible_facts.distribution }} ({{ ansible_facts.os_family }})"
          - "distribution version : {{ ansible_facts.distribution_major_version }}"
          - "ansible version      : {{ ansible_version.full }}"
          - "python version       : {{ ansible_python.version.major }}.{{ ansible_python.version.minor }}"
