---

- name: include OS specific configuration ({{ ansible_distribution }} ({{ ansible_os_family }}) {{ ansible_distribution_major_version }})
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      paths:
        - "vars"
      files:
        # eg. debian-10 / ubuntu-20.04 / centos-8 / oraclelinux-8
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
        # eg. archlinux-systemd / archlinux-openrc
        - "{{ ansible_distribution | lower }}-{{ ansible_service_mgr | lower }}.yml"
        # eg. debian / ubuntu / centos / oraclelinux
        - "{{ ansible_distribution | lower }}.yml"
        # eg. redhat / debian / archlinux
        - "{{ ansible_os_family | lower }}.yml"
        # artixlinux
        - "{{ ansible_os_family | lower | replace(' ', '') }}.yml"
      skip: true

- name: detect docker environment
  ansible.builtin.set_fact:
    is_docker_guest: "{{
      ansible_virtualization_role | default('host') == 'guest' and
      ansible_virtualization_type | default('none') == 'docker' }}"

- name: install requirements
  ansible.builtin.package:
    name: "{{ sshd_dependencies }}"
    state: present
  when:
    - sshd_dependencies | default([]) | count > 0

- name: gathering facts now
  ansible.builtin.setup:

- name: merge sshd configuration between defaults and custom
  ansible.builtin.set_fact:
    ssh_config: "{{ ssh_defaults_config | bodsch.core.merge_lists(ssh_config) }}"
    sshd_config: "{{ sshd_defaults_config | combine(sshd_config, recursive=True) | bodsch.core.sshd_values }}"

...
